# Generated by Django 4.2.3 on 2023-07-30 17:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subscriptions',
            new_name='subscription',
        ),
        migrations.AddField(
            model_name='order',
            name='invoice_id',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=uuid.uuid4, max_length=120),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CREATE', 'Создан'), ('SUCCESS', 'Успешно завершен'), ('CANCEL', 'Отменен')], default='CREATE', max_length=120),
        ),
    ]
