# Generated by Django 4.2.3 on 2023-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_tracker',
            field=models.IntegerField(default=0),
        ),
    ]
