# Generated by Django 4.2.3 on 2023-10-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_product_tarif_remove_subscription_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='count_minute',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('MOUNTH', 'месячная'), ('TIME', 'поминутная')], default='MOUNTH', max_length=120),
        ),
    ]
